
# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-browsers-legacy

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test



        version: 2.0

        jobs:
          build:
            docker:
              - image: cimg/openjdk:17.0.1
                auth:
                  username: mydockerhub-user
                  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
            steps:
              - checkout
              - restore_cache:
                  keys:
                    - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
                    - v1-dependencies- # fallback in case previous cache key is not found
              - run:
                - ./mvnw install -DskipTests
                - ./mvnw integration-test
              - save_cache:
                  paths:
                    - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}