jobs:
  build:
    docker:
      - image: cimg/ruby:3.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - run: |
          mvn install -DskipTests
          mvn dependency:go-offline
          mvn integration-test